### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/partner-contact#1353]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_partner_company_group - By @Highcooley - #1521
- [x] animal - By @Deriman-Alonso - #1736
- [x] base_country_state_translatable - By @AungKoKoLin1997 - #1411
- [x] base_location - By @pedrobaeza - #1361
- [x] base_location_geonames_import - By @pedrobaeza - #1385
- [x] base_location_nuts - By @edlopen - #1768
- [x] base_partner_company_group - By @Highcooley - #1504
- [x] base_partner_sequence - By @Nikul-OSI - #1453
- [x] crm_partner_company_group - By @Highcooley - #1510
- [x] partner_address_street3 - By @SodexisTeam - #1433
- [x] partner_address_two_lines - By @yankinmax - #1470
- [ ] partner_affiliate
- [x] partner_bank_code - By @hbrunn - #1550
- [x] partner_capital - By @EmilioPascual - #1547
- [x] partner_category_security - By @victoralmau - #1669
- [x] partner_category_security_crm - By @victoralmau - #1676
- [ ] partner_company_group
- [x] partner_company_type - By @apineux - #1355
- [x] partner_contact_access_link - By @vib-adhoc - #1390
- [x] partner_contact_address_default - By @Reyes4711-S73 - #1449
- [x] partner_contact_age_range - By @Highcooley - #1501
- [x] partner_contact_birthdate - By @carmenbianca - #1368
- [x] partner_contact_birthplace - By @Borruso - #1734
- [x] partner_contact_department - By @aiendry-aktivsoftware - #1556
- [x] partner_contact_gender - By @carmenbianca - #1369
- [x] partner_contact_in_several_companies - By @stephansainleger - #1852
- [x] partner_contact_job_position - By @carmenbianca - #1381
- [x] partner_contact_lang - By @pegonzalezspesol - #1370
- [x] partner_contact_nationality - By @marielejeune - #1380
- [x] partner_contact_personal_information_page - By @marielejeune - #1377
- [x] partner_contact_type_end_user - By @acsonefho - #1561
- [ ] partner_data_vies_populator - By @dreispt - #1642
- [x] partner_deduplicate_acl - By @SoporteOperu - #1524
- [x] partner_deduplicate_by_ref - By @SoporteOperu - #1525
- [x] partner_deduplicate_filter - By @stefan-tecnativa - #1589
- [x] partner_disable_gravatar - By @legalsylvain - #1388
- [x] partner_email_check - By @diogocsc - #1497
- [x] partner_email_duplicate_warn - By @victor-champonnois - #1423
- [ ] partner_employee_quantity - By @SoporteOperu - #1526
- [x] partner_external_map - By @imarulbala - #1419
- [x] partner_fax - By @BT-nfrancisco - #1442
- [x] partner_firstname - By @baimont - #1357
- [x] partner_helper - By @florian-dacosta - #1543
- [x] partner_identification - By @marielejeune - #1397
- [x] partner_identification_gln - By @QuocDuong1306 - #1573
- [x] partner_industry_parent - By @len-foss - #1835
- [x] partner_industry_secondary - By @victor-champonnois - #1418
- [x] partner_manual_rank - By @Reyes4711-S73 - #1448
- [x] partner_multi_relation - By @NL66278 - #1378
- [ ] partner_phone_extension
- [ ] partner_phone_secondary - By @emagdalenaC2i - #1420
- [ ] partner_phonecall_schedule - By @SoporteOperu - #1527
- [x] partner_pricelist_search - By @Highcooley - #1517
- [ ] partner_priority - By @kjoeldevk - #1392
- [x] partner_ref_unique - By @diogocsc - #1495
- [x] partner_second_lastname - By @FernandoRomera - #1422
- [x] partner_tz - By @rousseldenis - #1464
- [x] partner_vat_unique - By @AnizR - #1359
- [x] purchase_supplier_rank - By @amarcosg - #1538
- [x] sale_partner_company_group - By @Highcooley - #1520

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by pegonzalezspesol** [comment]
Migrated partner_contact_lang #1370

**Comment by vib-adhoc** [comment]
partner_contact_access_link - [1390](https://github.com/OCA/partner-contact/pull/1390)

**Comment by KM-joel** [comment]
@sbidoul 
@sbidoul 

Migration to version 16 

 - partner_priority #1392

**Comment by Vincenzo9191** [comment]
Migration to version 16.0 base_location_nuts

**Comment by imarulbala** [comment]
Migration to version 16.0

- partner_external_map https://github.com/OCA/partner-contact/pull/1419

**Comment by francesco-ooops** [comment]
@pedrobaeza can you pin this issue?

**Comment by BT-nfrancisco** [comment]
@sbidoul 
Migrated partner_fax  #1442

**Comment by yankinmax** [comment]
Migration to version 16.0
- [ ] https://github.com/OCA/partner-contact/pull/1470

**Comment by diogocsc** [comment]
partner_ref_unique: https://github.com/OCA/partner-contact/pull/1495

**Comment by diogocsc** [comment]
@sbidoul pls add to the list **partner_email_check**: https://github.com/OCA/partner-contact/tree/15.0/partner_email_check

**Comment by diogocsc** [comment]
partner_email_check: https://github.com/OCA/partner-contact/pull/1497

**Comment by amarcosg** [comment]
sale_customer_rank - https://github.com/OCA/partner-contact/pull/1536

**Comment by amarcosg** [comment]
purchase_supplier_rank - https://github.com/OCA/partner-contact/pull/1538

**Comment by pedroguirao** [comment]
partner_phonecall_schedule #1665

**Comment by Deriman-Alonso** [comment]
Working on animal #1736

**Comment by SirAionTech** [comment]
Please check `base_location_nuts`'s box: it has been migrated in https://github.com/OCA/partner-contact/pull/1768.

**Comment by adriapalleja** [comment]
Hi! I've been working in the migration of partner_priority, this is ready to review: https://github.com/OCA/partner-contact/pull/1722
