### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/partner-contact#184]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] account_partner_merge
- [x] ~~base_contact~~ - Deprecated and removed in #375
- [ ] base_continent
- [x] base_location @yvaucher #187 
- [x] base_location_geonames_import - @pedrobaeza #253
- [ ] base_location_nuts
- [x] base_partner_merge - By @yvaucher #274
- [x] base_partner_sequence - By @cubells - #358 
- [x] base_vat_sanitized - By @hbrunn - #364
- [ ] firstname_display_name_trigger
- [x] partner_address_street3 @gurneyalex #223 
- [ ] partner_auto_salesman
- [x] partner_changeset - By @leemannd - #357 
- [ ] partner_contact_address_detailed
- [x] partner_contact_birthdate @jt-xx #214 @leemannd #243 
- [x] partner_contact_gender @richard-willowit  #203
- [x] partner_contact_in_several_companies by @richard-willowit https://github.com/OCA/partner-contact/pull/197
- [x] partner_contact_lang - By @pedrobaeza - #356 
- [x] partner_contact_nationality @richard-willowit #205
- [x] partner_contact_personal_information_page by @richard-willowit https://github.com/OCA/partner-contact/pull/193 @jt-xx #214
- [x] partner_external_maps > renamed to partner_external_map #237 
- [x] partner_firstname  duplicate PR @yvaucher #238 (in fact there was already @alnslang #232 @kkarolis #215 )
- [x] partner_helper - By @hparfr - #412 
- [x] partner_relations > partner_multi_relation - ~~By to @idncom - #264~~ By @NL66278 - #304 
- [ ] partner_street_number @DarkoNikolovski #207
- [x] ~~passport @jt-xx #214~~ Module removed replaced by partner_identification
- [ ] portal_partner_merge
- [x] res_partner_affiliate - By @cubells - #368 
- [x] partner_sector - By @cubells - #329 
- [x] partner_contact_department - By @cubells - #327 
- [x] partner_contact_job_position - By @cubells - #328

**Comment by richard-willdooit** [comment]
OK, I have added two pull requests...

**Comment by elicoidal** [comment]
Great: will have a look later
Many thanks forthe contribution

**Comment by richard-willdooit** [comment]
@pedrobaeza @elicoidal 
Can we get the partner_contact_personal_information_page module merged as others depend on it that I wish to work on, and they are (will) fail the runbot.

**Comment by elicoidal** [comment]
Do you have a PR #?

**Comment by richard-willdooit** [comment]
#193

Also partner_contacts_in_several_companies is now #197 
And partner_contact_gender is #203

**Comment by elicoidal** [comment]
Thanks for the contribution.
I have had a look but need a tech guy to review the code

**Comment by richard-willdooit** [comment]
#205 partner_contact_nationality

**Comment by yvaucher** [comment]
Todo list updated

Thanks @richard-willowit for the work done here

**Comment by leemannd** [comment]
Migrating:
partner_contact_birthdate
https://github.com/OCA/partner-contact/pull/243

Corrections in partner_contact_bitrhdate

**Comment by leemannd** [comment]
@pedrobaeza @yvaucher port of partner_changeset from [8.0]. https://github.com/OCA/partner-contact/pull/357
It replaces https://github.com/OCA/partner-contact/pull/213 as it is not going forward from a long time.
