### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/partner-contact#309]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] account_partner_merge
- [x] ~~base_contact~~ - Removed as deprecated in #374 
- [ ] base_continent - By @qtheuret - #544 
- [x] base_location - By @OpenCode - #317 
- [x] base_location_geonames_import - By @alexis-via - #320 
- [x] base_location_nuts - By @chienandalu - #432 
- [x] base_partner_merge - By @alan196 - #445 
- [x] base_partner_sequence - By @grindtildeath - #359 
- [x] base_vat_sanitized - By @alexis-via - #343 
- [ ] firstname_display_name_trigger
- [x] partner_address_street3 - By @alexis-via - #318 
- [ ] partner_auto_salesman
- [x] partner_capital - By @chienandalu - #427
- [x] partner_changeset By @yvaucher #380
- [x] partner_created_by_vat - By @feketemihai - #325 
- [ ] partner_contact_address_detailed
- [x] partner_contact_birthdate - By @invitu - #315
- [x] partner_contact_gender - By @invitu - #315
- [x] partner_contact_lang - By @cubells - #472 
- [x] partner_contact_in_several_companies - By @njeudy - #347 
- [x] partner_contact_nationality - By @rousseldenis - #371 
- [x] partner_contact_personal_information_page - By @invitu - #315
- [ ] partner_default_sale_discount - By @lbelorgey - #683 
- [x] partner_external_map - By @alexis-via - #319 
- [x] partner_financial_risk - By @salvatoretrimarchi - #360
- [x] partner_firstname - By @sylvain-garancher - #311 
- [x] partner_helper - By @EBII - #386 
- [x] partner_identification - By @jjscarafia - #324 
- [x] partner_phone_extension - By @nikul-serpentcs - #457 
- [x] partner_multi_relation - By @NL66278 - #363 
- [x] partner_sale_risk - ~~By @Ehtaga - #452~~ - By @chienandalu - #589 
- [x] partner_second_lastname - By @pedrobaeza - #437 
- [x] partner_sector - By @luismontalba - #424 
- [x] partner_stock_risk - By @chienandalu - #456 
- [x] partner_street_number - By @astirpe - #314 
- [x] ~~passport~~ - Removed since v9
- [ ] portal_partner_merge
- [x] res_partner_affiliate - Renamed to partner_affiliate - By @lasley - #438

**Comment by Garamotte** [comment]
Migration of partner_firstname here : https://github.com/OCA/partner-contact/pull/311

**Comment by cvinh** [comment]
partner_contact_gender, partner_contact_birthdate, partner_contact_personal_information here : https://github.com/OCA/partner-contact/pull/315

**Comment by alexis-via** [comment]
Migration of partner_external_maps: https://github.com/OCA/partner-contact/pull/319
Migration of partner_address_street3: https://github.com/OCA/partner-contact/pull/318

**Comment by Giuliano69** [comment]
Hi,
may I ask if the passport module has been removed because of being incorporated in other module or because of other problems ?
It may be needed in case of invoicing to ETRA EU customer (vat exemption - passport number mandatory  in customer data)

Thanks for your help

**Comment by njeudy** [comment]
partner_contact_in_several_company here: #347

**Comment by njeudy** [comment]
Anyone to review #347  ? code is ready ;)

**Comment by yvaucher** [comment]
added partner_changeset to the list: https://github.com/OCA/partner-contact/tree/9.0/partner_changeset

**Comment by tarteo** [comment]
Hello,
Is there a reason why base_vat_sanitized is not on the list?

Thanks in advance! :)

**Comment by pedrobaeza** [comment]
Because it was not present in 9.0 when we migrate the 10.0 branch.

**Comment by tarteo** [comment]
@pedrobaeza Okay!

**Comment by tarteo** [comment]
@pedrobaeza Can I migrate base_vat_sanitized?

**Comment by pedrobaeza** [comment]
It's already migrated in https://github.com/OCA/partner-contact/pull/343. I'm adding to the list.

**Comment by tarteo** [comment]
@pedrobaeza Thanks!! :)

**Comment by paulius-sladkevicius** [comment]
@pedrobaeza similar question, why partner_sector is not in the list?

**Comment by cvinh** [comment]
@paulius-sladkevicius @pedrobaeza is on holidays... I hope he is having a big breath ;-)
partner_sector has been added to 9.0 branch on November 2016. The 10.0 branch has been created end of October 2016 so partner_sector was not in 9.0 branch at that time.
I think good practise is to do a PR to add partner_sector in 10.0 branch (with installable = False) and then do another PR for migration to 10.0

**Comment by lasley** [comment]
Wow @pedrobaeza on holidays?! I didn't feel like this could ever happen! Get some rest, friend 😄 

@invitu @paulius-sladkevicius We should just add the missing modules to the list, there's no reason to create two PRs. Our [v10 migration instructions](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0) should be all that's needed in regards to the actual migration.

@OCA/crm-sales-marketing-maintainers - Can you add `partner_sector` to the list of modules that need to be upgraded, please and thanks!

**Comment by pedrobaeza** [comment]
I'm on holidays but still keep an eye for these quick tasks :wink:

Added module to the list

**Comment by cvinh** [comment]
@lasley The reason to add the unmigrated module in separate PR is to better see the diff when migrate is done (thanks to @legalsylvain )

**Comment by cvinh** [comment]
@pedrobaeza on holidays but still not sleeping ;-)

**Comment by lasley** [comment]
@invitu - Hmmm I see where you're coming from with that. I just look at a manual diff, but that was a process I had to learn and I admit wasn't that obvious.

The current process is to do the migration in one PR. Changing it is a fairly far reaching proposal, so I think it would be best if you submitted an RFC (issue) to the [maintainer-tools](https://github.com/OCA/maintainer-tools/issues) repo, or directly submit the proposal as a PR against the contribution docs in the same repo. This way we can discuss it in context, and allow stakeholders to expose all points.

**Comment by cvinh** [comment]
@lasley my comment comes from https://github.com/OCA/pos/pull/154#issuecomment-282669089

**Comment by lasley** [comment]
@invitu - we can discuss there, I believe you misunderstood

**Comment by invitu** [comment]
@lasley I opened a issue here https://github.com/OCA/maintainer-tools/issues/261

**Comment by alan196** [comment]
Migration of base_partner_merge in #445

**Comment by BT-aestebanez** [comment]
The module `partner_identification_gln` should be in the list of items: https://github.com/OCA/partner-contact/pull/666
