### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/partner-contact#482]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_partner_merge
- [ ] base_continent - By @awwea - #523
- [x] base_country_state_translatable - By @yostashiro - #537 
- [x] base_location - By @etobella - #488 
- [x] base_location_geonames_import - By @jbeficent - #494 
- [x] base_location_nuts - By @agaldona - #518 
- [x] base_partner_merge - By @JayVora-SerpentCS - #545 
- [x] base_partner_sequence - By @jesusVMayor - #531
- [x] base_vat_sanitized - By @astirpe - #552 
- [ ] firstname_display_name_trigger
- [x] partner_academic_title - By @luismontalba - #719 
- [x] partner_address_street3 - By @huyly0909 - #565 
- [x] partner_affiliate - By @BT-rmartin - #579 
- [ ] partner_alias
- [ ] partner_auto_salesman - By @JayVora-SerpentCS - #542 
- [ ] partner_capital - By @remihb - #661 
- [x] partner_coc - By @astirpe - #611 
- [x] partner_company_type - By @daramousk - #660
- [ ] partner_contact_address_detailed
- [x] partner_contact_birthdate - ~~By @jprobineau - #509~~ By @Olivier-LAURENT - #617 
- [x] ~~partner_contact_configuration~~ Not needed anymore
- [x] partner_contact_department - By @mreficent - #620 
- [x] partner_contact_gender - ~~By @jprobineau - #510~~ By @NL66278 - #662 
- [x] partner_contact_in_several_companies - By @njeudy - #507 
- [x] partner_contact_job_position - By @mreficent - #621 
- [x] partner_contact_lang - By @cristinamartinrod - #636
- [ ] partner_contact_nationality - By @jprobineau - #512 
- [ ] partner_contact_nutrition
- [ ] partner_contact_nutrition_goal
- [x] partner_contact_personal_information_page - ~~By @jprobineau - #511~~ By @njeudy - #507
- [ ] partner_contact_role - By @simahawk - #524
- [ ] partner_contact_weight
- [x] ~~partner_create_by_vat~~ - ~~Same as Odoo core base_vat_autocomplete~~
- [ ] partner_email_check - By @denislour - #543
- [x] partner_employee_quantity - By @pedrobaeza - #655 
- [x] partner_external_map - By @pedrobaeza - #505 
- [x] partner_financial_risk > account_financial_risk - By @carlosdauden - OCA/credit-control#2
- [x] partner_firstname - By @etobella - #487 
- [ ] partner_helper
- [x] partner_identification - By @simahawk - #526 
- [x] partner_multi_relation - By @ddufresne - #564 
- [x] partner_noncommercial - By @lfreeke - #657
- [ ] partner_password_reset
- [x] partner_phone_extension - By @JayVora-SerpentCS - #549 
- [x] partner_phonecall_schedule - By @chienandalu - #606 
- [x] partner_ref_unique - By @cristinamartinrod - #626
- [x] partner_sale_risk > sale_financial_risk - By @carlosdauden - OCA/credit-control#3
- [x] partner_second_lastname - By @jbeficent - #495 
- [x] partner_sector > partner_industry_secondary - By @mreficent - #619 
- [x] ~~partner_street_number~~ - Covered in core with base_address_extended module
- [x] partner_stock_risk > stocklfinancial_risk - By @carlosdauden - OCA/credit-control#4
- [x] partner_vat_unique - By @michotm - #616 
- [ ] portal_partner_merge - By @JayVora-SerpentCS - #546

**Comment by feketemihai** [comment]
partner_create_by_vat will not be migrated, Odoo's module "base_vat_autocomplete" is doing the same things...should i do something else since the module will be deprecated?

**Comment by pedrobaeza** [comment]
OK, noted

**Comment by njeudy** [comment]
@pedrobaeza :  partner_contact_in_several_companies and partner_contact_personal_information_page

#507

**Comment by bouvyd** [comment]
Seems like `partner_company_type` does mostly the same thing as `res.partner.industry` model introduced in 11.0 at odoo/odoo@9a572f8eec67e78d76798c43b014f21e8a9dfdef

I'll leave you the judge of that though

**Edit:** perhaps it's actually `partner_sector` that is impacted. Honestly not sure about the functional difference between those two.

**Comment by jprobineau** [comment]
@pedrobaeza : partner_contact_birthdate, partner_contact_gender, partner_contact_nationality, partner_contact_personal_information_page

**Comment by emagdalenaC2i** [comment]
@dbo-odoo I agree, partner_sector is like res.partner.industry introduced in Odoo 11. You can manage the sectors / industry types in: Contacts --> Configuration --> Sectors of activity

**Comment by yajo** [comment]
Then it should get migrated by OpenUpgrade possibly.

**Comment by pedrobaeza** [comment]
Well, there's no 1:1 feature mapping, as parner_sector includes a many2many field for indicating secondary sectors, and also the included sector in standard data is not what everyone can consider as their current sectors. To be investigated further...

**Comment by astirpe** [comment]
The functionality provided by module `partner_street_number` is completely covered by standard module `base_address_extended`.

Can we remove `partner_street_number` from the list of modules to be ported?

**Comment by pedrobaeza** [comment]
We should analyze it then in OpenUpgrade for a smooth migration from v10 `partner_street_number` to v11 `base_address_extended`. Any way, I strike-through the line.

**Comment by simahawk** [comment]
partner_identification @simahawk #526

**Comment by jesusVMayor** [comment]
base_partner_sequence https://github.com/OCA/partner-contact/pull/531

**Comment by JayVora-SerpentCS** [comment]
partner_auto_salesman #542

**Comment by JayVora-SerpentCS** [comment]
base_partner_merge #545

**Comment by JayVora-SerpentCS** [comment]
portal_partner_merge #546

**Comment by astirpe** [comment]
base_vat_sanitized #552

**Comment by andreschenkels** [comment]
It seems like most migrations to v11 stopped for partner-contact anything I can do here?

**Comment by pedrobaeza** [comment]
Well, if you are interested in any module, you can:

- Review the PR if it's already proposed.
- Migrate a module and propose a PR.

**Comment by ddufresne** [comment]
I would like to contribute on the migration of partner_multi_relation. I could do this tomorrow.

@NL66278 have you already begin at Therp ?

**Comment by NL66278** [comment]
@ddufresne We have not started migration to 11.0, but we still have an outstanding PR for 10.0 that has a refactoring for easier extention. If you migrate, I would suggest to take that as a starting point. https://github.com/OCA/partner-contact/pull/497

**Comment by ddufresne** [comment]
@NL66278 sure, already gave my thumbs up for the refactoring. I will start from there.

**Comment by ddufresne** [comment]
partner_multi_relation https://github.com/OCA/partner-contact/pull/564

**Comment by astirpe** [comment]
partner_coc #611

**Comment by NL66278** [comment]
@pedrobaeza partner_contact_gender now migrated here: https://github.com/OCA/partner-contact/pull/662. There is a message about Yairo Llopez not having signed the CLA, but this is about existing code already merged in other branches. Besides that, I think it is more of a problem of changed email or something like that.

**Comment by pedrobaeza** [comment]
About the CLA claim, it's because the CLA bot has been reworked recently because it was not working correctly, so maybe some missing CLAs that weren't detected previously are now claimed. There's also another fact: on v6.1/v7, when OCA started, there was a massive dump of existing module from openerp-extra mega-repository without claiming the CLA, and now as we are importing full commit history, this might arise again. Don't worry about that, and we will normalize missing CLAs step by step.

**Comment by emagdalenaC2i** [comment]
partner_contact_personal_information_page - By @jprobineau - #511 is closed and superseded By @njeudy  - #507 that is already merged (there are the migration of partner_contact_personal_information_page and partner_contact_in_several_companies in the same PR)

Please, check in the list partner_sector - By @mreficent - #619 because it is already merged and renamed as -> partner_industry_secondary

check in the list partner_contact_lang - By @cristinamartinrod - #636 

Please add to the list partner_ref_unique - By @cristinamartinrod - #626 that is already migrated and merged

There is a PR for the migration of partner_company_type - By @daramousk - #660 

Please, add to the list partner_noncommercial - By @lfreeke - #657 

Please, add to the list partner_email_check - By @denislour - #543 

Please, add to the list partner_contact_role - By @simahawk - #524 

Please, add to the list base_continent - By @awwea - #523

**Comment by luismontalba** [comment]
It seems that partner_contact_configuration is not needed in V11 because these menus are included in the contacts module in core, and they are available for any user included in group base.group_system

**Comment by pedrobaeza** [comment]
OK, thanks for noting it

**Comment by luismontalba** [comment]
partner_academic_title migrated in #719

**Comment by emagdalenaC2i** [comment]
Please, check partner_academic_title - By @luismontalba - #719 that is already merged

**Comment by NL66278** [comment]
Unfortunately partner_street_number is not completely covered by base_address_extended, as in that module the street fields are not split for contacts in the main partner form...
